class CreateKine < ActiveRecord::Migration
  def change
    create_table :kine do |t|
      t.string :name
      t.integer :ear
      t.datetime :birth
      t.integer :owner_id
      t.integer :t01
      t.integer :t02
      t.integer :t03
      t.integer :t04
      t.integer :t05
      t.integer :t06
      t.integer :t07
      t.integer :t08
      t.integer :t09
      t.integer :t10
      t.integer :t11
      t.integer :t12
      t.integer :t13
      t.integer :t14
      t.integer :t15
      t.integer :t16
      t.integer :t17
      t.integer :t18
      t.integer :t19
      t.integer :t20
      t.integer :t21
      t.integer :t22
      t.integer :t23
      t.integer :t24
      t.integer :t25
      t.integer :t26
      t.integer :t27
      t.integer :t28
      t.integer :t29
      t.integer :t30
      t.integer :t31
      t.integer :t32
      t.integer :t33
      t.integer :t34
      t.integer :t35
      t.integer :t36
      t.integer :t37
      t.integer :t38
      t.integer :t39
      t.integer :t40
      t.integer :t41
      t.integer :t42
      t.integer :t43
      t.integer :t44
      t.integer :t45
      t.integer :t46
      t.integer :t47
      t.integer :t48
      t.integer :t49
      t.integer :t50
      t.integer :t51
      t.integer :t52
      t.integer :t53
      t.integer :t54
      t.integer :t55
      t.integer :t56
      t.integer :t57
      t.integer :t58
      t.integer :t59
      t.integer :t60
      t.integer :t61
      t.integer :t62
      t.integer :t63
      t.integer :t64
      t.integer :t65
      t.integer :t66
      t.integer :t67
      t.integer :t68
      t.integer :t69
      t.integer :t70
      t.integer :t71
      t.integer :t72
      t.integer :t73
      t.integer :t74
      t.integer :t75
      t.integer :t76
      t.integer :t77
      t.integer :t78
      t.integer :t79
      t.integer :t80
      t.integer :t81
      t.integer :t82
      t.integer :t83
      t.integer :t84
      t.integer :t85
      t.integer :t86
      t.integer :t87
      t.integer :t88
      t.integer :t89
      t.integer :t90
      t.integer :t91
      t.integer :t92
      t.integer :t93
      t.integer :t94
      t.integer :t95
      t.integer :t96
      t.integer :t97
      t.integer :t98
      t.integer :t99

      t.timestamps
    end
  end
end
